version: '3'

services:
  app:
    build: 
      context: .
    ports:
     - "7000"
  nginx:
      image: nginx:latest
      volumes :
        - ./conf/challenge.nginx:/etc/nginx/nginx.conf:ro
      depends_on:
        - app
      ports:
        - "80:80"  
